### ISSUE TITLE
[FR] 被选择的内容不要显示下划线

### ISSUE THREAD

**Issue by wwjCMP** [LincZero/obsidian-any-block#28]
显示下划线真的很影响美观和阅读，希望可以增加一个取消显示按钮

**Comment by LincZero** [comment]
可以先用 css 解决，最近没空维护

**Comment by LincZero** [comment]
下划线是为了标注范围，让你知道这段内容在选择器的选择范围里面。

但下划线过于丑陋的问题确实存在，将下划线设置了没那么亮眼的颜色 + 20%的透明度

fde12a36e75251298fee17c4c60aa5b83f85c69e

自定义该下划线的方式：（可在插件的css文件/ob整体样式的css/ob的样式片段器上加）

```css
.ab-line-yellow {
    text-decoration: none !important;
}
```
