### ISSUE TITLE
[咨询]演示中的表格内容垂直居中是插件的功能吗

### ISSUE THREAD

**Issue by hsingll** [LincZero/obsidian-any-block#40]
如![转树表格](https://github.com/LincZero/obsidian-any-block/blob/main/docs/zh/png/list2table.png?raw=true)

我在使用中没有垂直居中，如果是的话，报一个bug。

目前用css实现：
```css
body {
  --table-cell-vertical-alignment: middle;
}
.table-cell-wrapper {height: unset !important;}
```
