### ISSUE TITLE
addClass会改变在mermaid的代码块的结构

### ISSUE THREAD

**Issue by turbidsoul** [LincZero/obsidian-any-block#43]
![图片](https://github.com/user-attachments/assets/cdab91df-503a-4e2e-bb8a-7792f27ab7de)
![图片](https://github.com/user-attachments/assets/2337693a-bf89-46ae-be0f-047c9b391c94)
![图片](https://github.com/user-attachments/assets/645756d2-9342-418f-82ab-f15410689f91)

请忽略截图中的红框，刚开始以为是改了class造成的，仔细看是代码结构变了，经过测试是结构变了

```css
.w100 {
  width: 100% !important;
  
  .mermaid {
    text-align: center !important;
    svg  {
      max-width: 100% !important;
    }
  }
}

```

我写的这个样式无法生效
